### ISSUE TITLE
Support Subscribe to Abjjad UI

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#10]
UI should be like Anghami APP

**Comment by EmanHylooz** [comment]
- the pagr اشتراكي to be native from IOS not web view

**Comment by EmanHylooz** [comment]
Some changes in the UI might be needed, I will provide a new design elements after consulting with Nur from marketing team.

**Comment by EmanHylooz** [comment]
Text: 

اشتراك" أبجد بلا حدود" الشهري


فترة تجريبية مجانية
تحميل الكتب بلا حدود
قراءة بلا انترنت


ًابدأ أسبوعك الأول مجانا
٣.٩٩ دولار فقط شهرياً بعد نهاية التجربة المجانية


![unnamed 2](https://cloud.githubusercontent.com/assets/6830380/23106113/2f9a5d80-f6f1-11e6-8cbe-788ed994a917.png)

**Comment by EmanHylooz** [comment]
Was it done as per the excel sheet? As I cannot see it

P.S: This should become ابدأ شهرك الأوّل مجاناً

**Comment by EmanHylooz** [comment]
1. The button is corrupted on my screen. (maybe because my screen is small)
2. The page does not scroll down.. so I cannot see the "٥.٩٩ دولار فقط شهرياً بعد نهاية التجربة المجانية"

![img_5058](https://cloud.githubusercontent.com/assets/6830380/23223040/86487142-f932-11e6-8e0a-1a59273fbe88.PNG)

**Comment by Shimaa-Hassan** [comment]
Done

**Comment by EmanHylooz** [comment]
I sent the details in an email

**Comment by EmanHylooz** [comment]
Our marketing team did a new design for this page. It has more images, new logo, some changes in color. Nothing related to functionality, only changes in design. 

The design is done in AI, so you can extract all the elements, colors, font, images. No need to design from scratch, just take the elements the way they are. 

I will send you the AI file by email once you start on this task as I cannot attach it here. For the time being the JPG file is attached (please don't use it for design, use the AI file). This is only for view.
![final sub page1](https://cloud.githubusercontent.com/assets/6830380/23660942/bd26b874-0353-11e7-8b4f-9c26c0b4550b.png)

**Comment by Shimaa-Hassan** [comment]
Share design in Google drive with 
eman.refaat@tagipedia.com
shimaa.hassan@tagipedia.com

**Comment by EmanHylooz** [comment]
Done.

**Comment by EmanHylooz** [comment]
The in app purchase is not working in the test flight.
