### ISSUE TITLE
billing testing

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#100]
https://developer.android.com/google/play/billing/billing_testing.html

Hello Google Play Developer,

We’re writing to let you know about a change to test subscription order IDs.

On July 10, 2017, we’ll start providing order IDs for test subscriptions and renewals. Previously, we did not create an order for test subscriptions, so there was no order ID. We will also be backfilling existing test subscriptions to include order IDs.

Action recommended: If you use test subscriptions, make sure the presence of the orderId field won’t cause any issues with your code.

Test subscription order IDs should enable you to test your purchasing system end-to-end without needing to use real currency.

You can learn more about testing in-app purchases in the Android Developers Help Center. The documentation will be updated before July 10th to reflect the change to order IDs.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan is this done or we need to do more about it?
