### ISSUE TITLE
Branch Integration 

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Technical#107]
@Shimaa-Hassan, we discovered that Branch is not tracking any Andriod installs. Though we have a great amount of clicks, we kept getting 0 installs so tested and the problem is that its not tracking it all together. 

Can you please check  it, and while at it also test web and iOS are tracking accurately? 
![img_5110](https://user-images.githubusercontent.com/29916678/27911541-0cd9d488-6262-11e7-936b-9ee011003811.JPG)

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez  please add mahmoud.ali@tagipedia.com to branch app

**Comment by Nur-alfayez** [comment]
Done.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan How can we test this on beta? Is there a way? Please explain the steps of testing.

**Comment by Nur-alfayez** [comment]
Yeah, because there are no installs from Android yet on any of the existing links we're tracking - do you think we need new links?

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez we should test installs when app will be available in store

**Comment by Nur-alfayez** [comment]
Will do that. Thanks Shimaa.

**Comment by Nur-alfayez** [comment]
Hi Shimaa,

We tested it, it only tracks re-opens and not installs. But what does re-open mean anyway? a store ID, or registered app user, or device?

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan we got some installs, did you do any fixes?

**Comment by Shimaa-Hassan** [comment]
No I didn't do anything after add it to store.
So I think it track installs when app put in store.
don't forget to close issue if no bugs.
