### ISSUE TITLE
Automated Email for free trial users from web (24/8/2017)

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Technical#111]
Check a tool to send 1 text based automated email for users that start free trial from web.

**Comment by MahmoudAlyIbrahim** [comment]
@Nur-alfayez , will the free trial e-mail will be sent to the users that are currently in the free trial period too , or only the users that will subscribe in the feature. 

Also, i need the email template

**Comment by Nur-alfayez** [comment]
It will sent automatically the minute a user subscribes to the free trial on web so basically future ones. It will be mostly text based. I'll send you the email content very soon.

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan @MahmoudAlyIbrahim please find the email text here: https://docs.google.com/document/d/1HFgzIscPNFLW8_hyI59okMXHmW8RgZofMx22wgnoJwk/edit#heading=h.6boe9dyn1454. 

The app store buttons need to be linked to the app on store links. 

Please share a preview with me before we start sending it. 
Thanks

**Comment by MahmoudAlyIbrahim** [comment]
@Nur-alfayez i noticed that every email in the website have two templates (english one and arabic one), just wanted to know, is there is an english template for this email? or just arabic one?

**Comment by EmanHylooz** [comment]
@Nur-alfayez will be deployed today and @Shimaa-Hassan will let you know once it is done (we agreed to have it Arabic only)

**Comment by Nur-alfayez** [comment]
Great!

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan is this ready for testing?

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz it is in production Now so it is ReadyForTesting
