### ISSUE TITLE
Forgot password and all sending emails is not working 

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#114]
The forget password is not sending an email.. and now I noticed no email sending from abjjad notofocations.. so can you check this area too? We use Amazon for email sending so maybe something wrong happened there?

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz what about using this service instead of amazon https://sendgrid.com/ ?

**Comment by EmanHylooz** [comment]
I dont mind but is it same price? And does it need re intehration?
Meaning.. is it faster and easier and more reliable than just solving the
amazon problem?

On Jul 24, 2017 11:32, "Shimaa Hassan" <notifications@github.com> wrote:

@EmanHylooz <https://github.com/emanhylooz> what about using this service
instead of amazon https://sendgrid.com/ ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EmanHylooz/Abjjad/issues/114#issuecomment-317354885>,
or mute the thread

**Comment by Shimaa-Hassan** [comment]
https://sendgrid.com/pricing/

**Comment by Shimaa-Hassan** [comment]
Development is very easy and fast and have freetrial "Send up to 40,000 emails for free with our 30-day trial—no credit card required." so we can test it.
