### ISSUE TITLE
Free trial pop up - Cannot subscribe on Android

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#116]
And for android.. when i get the pop ip and click ابدا التجربة المجانية i get this (attached) . So cannot test it.. advice? 

![screenshot_20170718-172833](https://user-images.githubusercontent.com/6830380/28323821-8587a232-6be2-11e7-8e47-0fb01c51e0d4.png)

**Comment by MahmoudAlyIbrahim** [comment]
you cannot buy something from yourself, so you need to use another account, not the google play administrator account

**Comment by EmanHylooz** [comment]
Please send me an account I can use for testing, and the apk as I cannot download the Android test app unless I am signed in with emanhylooz@abjjad.com

In summary, please send me the steps and credentials to be able to test it

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan as agreed, please  add me as a tester on emanhylooz@gmail.com on Android beta so i can test the subscription.

**Comment by Shimaa-Hassan** [comment]
Added

**Comment by EmanHylooz** [comment]
For some reason I cannot find it in beta when i sign in through emanhylooz@gmail.com! 
If it is easier to send me an alk, please do

**Comment by Shimaa-Hassan** [comment]
Sorry just saw it
please click in this link while you logged in as emanhylooz@gmail.com
https://play.google.com/apps/testing/com.abjjad.app

**Comment by Shimaa-Hassan** [comment]
And press start testing as tester should do it when first testing app

**Comment by EmanHylooz** [comment]
I just tested it and the same problem as IOS appeaes. The user sunscribes
through the pop up but the lock on the ebooks stays the same. (Screen shot
attached)

**Comment by Shimaa-Hassan** [comment]
Solved in both IOS, android
