### ISSUE TITLE
A user subscribed through iTunes in App Purchase but his subscription status = 0

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#125]
There is a user who had the following problem: 

1. He sigend in to the app 
2. Started his free trial through in app purchase in iPhone 
3. His subscription status remains zero (although he got confirmation from itunes that his free trial started) 
4. I asked him to cancel his subscription from iTunes and subscribe again from abjjad 
5. Same problem remains , subscription status=0 

To solve the problem fast, I just went to the database and updated his subscription status to 1 instead of zero so he can read books, but the problem remains that he wont be a subscriber in abjjad. 

Here are the photos he has: 

![user 1](https://user-images.githubusercontent.com/6830380/28746850-0d7a9bf2-749b-11e7-87b5-f920d85ad8ca.jpg)
![user 2](https://user-images.githubusercontent.com/6830380/28746851-0d7ada0e-749b-11e7-8b07-794b99ce6853.jpg)
![user 3](https://user-images.githubusercontent.com/6830380/28746854-0d7ca14a-749b-11e7-96ef-37a1eba4d965.jpg)
![user 4](https://user-images.githubusercontent.com/6830380/28746852-0d7c84c6-749b-11e7-9641-10e587c6fdf2.jpg)
![user 5](https://user-images.githubusercontent.com/6830380/28746853-0d7c94de-749b-11e7-88fa-cb69041983cf.jpg)

**Comment by EmanHylooz** [comment]
Here are the user info from the data base: 

[User Info.xlsx](https://github.com/EmanHylooz/Abjjad/files/1185105/User.Info.xlsx)

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  what about making call after find the problem as currently in debugging mode ?

**Comment by EmanHylooz** [comment]
Yes sure but I just needed to explain to you that I reproduced the bug in a way, and also I am looking into the database data and there is something weird about how itunes in app purchasing is showing different numbers... thought that this might help you in debugging.

**Comment by Shimaa-Hassan** [comment]
Ok :) I'm waiting for your call
