### ISSUE TITLE
User is unable to turn off the notification in Android

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#128]
Here is the explanation: 

![complain for android notifications](https://user-images.githubusercontent.com/6830380/28753852-e1782ad0-7542-11e7-88a2-ae687a3d48f9.png)

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz for fast solution user can turn off notification from his mobile
1- In Device Settings menu, head down to “Apps.”
2- In this list, scroll until you find abjjad, then tap on it. There will be a little checkbox titled “Show notifications,” that’s your setting—give it a tap to turn off all notifications from abjjad.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan Thank you for the steps, what is the long solution? 
Since it is working ( i assume?) in IOS, so isn't it just integrating some sort of an API?

**Comment by Shimaa-Hassan** [comment]
The another solution is simple that we disable notification when user uncheck check box on abjjad setting. but we need to  release new version.

**Comment by Shimaa-Hassan** [comment]
IOS Also have the same steps to disable notifications for app from device.

**Comment by EmanHylooz** [comment]
Yes, let's solve it then and make it like IOS and keep it for the next
release. (I shared with the users the steps as a temp solution for now).

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>
