### ISSUE TITLE
Clearing the list of the last 52,000 emails we have 

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#129]
We agreed on checking with https://www.email-validator.net/ about the clearing lists they have (I sent them an email and waiting their reply). 

If this did not work, we will do the work around by using a different tool to send them emails and check on the hard bounce.

**Comment by EmanHylooz** [comment]
A one-time validation for 52,000 email addresses costs EUR 254 / USD
306.80.

We offer two different validation modes (both at the same price):
- Express Check (retries unavailable mail servers for 2 hours)
  -> max 2 hours turnaround time
- Full Check (retries unavailable mail servers for up to 72 hours)
  -> max 72 hours turnaround time

You can start by uploading your email list as CSV file directly here
(log into your account first):
https://www.email-validator.net/email-list-validation-cleaning.html

As a result you receive a CSV file with detailed validation results
for all email address on your list.

Order is done here: https://order.shareit.com/cart/view

**Comment by EmanHylooz** [comment]
We are getting more of the emails such as: "00115de39381416aa909b344a9f3875c@autogen.com" 
Currently the count reach around 2,200 email. 
So we need to run a script or some sort of an automated thing that would mark them as hard bounce. 

Check here: 
select count(*) from members where email like '%autogen%'

And we we will be getting more of those further on, so we need to protect ourselves from Amazon as all those will bounce out eventually.

**Comment by Shimaa-Hassan** [comment]
Don't worry I already forbidden sending for abjjad autogenerating emails. we don't need any other scripts for it.

**Comment by EmanHylooz** [comment]
You are amazing :)

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan we need to run it from email-validator to test 100 emails and then run on all 50K email

**Comment by EmanHylooz** [comment]
Already solved the problem through Sendy, they did a free verification for the emails, and the list is now clean in our data base.
