### ISSUE TITLE
Urgent - Appsflyer Bug

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#130]
Please check the email sent via Farah. (Subject: Urgent - Appsflyer Bug). 

Seems that the last update we had on IOS did something wrong with AppsFlyer SDK.

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz @Farahalfayez finally solved we will upload new IOS version soon ISA.

**Comment by EmanHylooz** [comment]
Yaaaaaaaay !
