### ISSUE TITLE
Problem with Branch Links on Android

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#131]
Please check Farah email (subject: Problem with Branch Links on Android)

**Comment by MahmoudAlyIbrahim** [comment]
i tested the link in the screenshot : https://abjjadltd.app.link/IwkbScm6tE and it works well, it is not an issue with branch but when using built-in browser of old version of facebook app (isn't it?) and they solved it, so no worries

**Comment by EmanHylooz** [comment]
The user sent the problem just today. So it is not solved.
I face the same issue although my browser is not old. At first ot always
gives me page cannot load.. then after seconds it opens.
This is from instagram app... but all other links gives me the same.

**Comment by MahmoudAlyIbrahim** [comment]
Ok, i got it

**Comment by EmanHylooz** [comment]
@Farahalfayez 
What about in branch link to send the user in all cases to the itunes store or the android store, even for those who has the app downloaded. This way the old user who has the app downloaded (but not updated), will be directed to the store where they will see the button "update" and they will update it.

**Comment by Farahalfayez** [comment]
@EmanHylooz Sure I can do that.

**Comment by Farahalfayez** [comment]
@EmanHylooz I will have to manually change all the previous ones by going over them one by one.. do you want me to do that or you mean the future links?

**Comment by EmanHylooz** [comment]
Howwa the old ones will be used all the time for social media and ads msh
haik? If we will still be using them maybe it is better to change them
right?

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Farahalfayez** [comment]
Ok no problem I will change them.

**Comment by Farahalfayez** [comment]
@EmanHylooz Just to make sure, the link will try to open a web page (itunes or google play) then it will show a popup saying "this page will open in another application" and you have the choice to click open or cancel. Is that fine?

**Comment by EmanHylooz** [comment]
Oh, can you do an example and send it to me to see all the cases first? I
thought it would only open the store and that's it.

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Farahalfayez** [comment]
Here's a test link: https://abjjadltd.app.link/HhThsHDOMF @EmanHylooz

**Comment by EmanHylooz** [comment]
​I checked it on Android, it opened the google play sore smoothly without
any warning messages. I tried it from iPhone, it launched the app, can you
send me another test where in IOS it would open the iTunes store instead? ​

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Farahalfayez** [comment]
![unnamed 1](https://user-images.githubusercontent.com/30770652/29509911-ec568102-866a-11e7-804e-15c3dabda5d9.jpg)
That's weird. I opened it on my phone and I got this: 
![unnamed](https://user-images.githubusercontent.com/30770652/29509907-e742e516-866a-11e7-85d0-1f2b60480db3.jpg)

**Comment by EmanHylooz** [comment]
I tested it while the application is downloaded on my iphone, and it just
relaunched the app instead of opening itunes store.
Just now I uninstalled the app and clicked on the link, it showed me a
message saying "open in itunes store?" I clicked yes and it took me to
itunes store. But this is weird, what is the difference between this link
and previous links we have in the case that the user have the app
uninstalled? We did not change this part, we only want to change the part
where when the app is installed not to relaunch it and instead to open
itunes store again.

By the way, I checked again the old link we have on instagram and it gave
me same message, seems this is something new from itunes. So we cannot do
anything about it.

But can we have a test link again where when the app is installed it will
open itunes?

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
in the case that the user have the app uninstalled?*

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
in the case that the user have the app installed?* LOL

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Farahalfayez** [comment]
Lol. 3ajagteeni Eman. The screenshot I sent is from my phone and I have the app installed but it opened it in web then redirected me to Appstore. Don't know why you didn't get the same thing honestly. Hala2 in the settings of the whole account there is an option to "always try to open app" I unchecked that because we wanted to open the appstore instead even when the app is installed. This is why maybe all links now are opening itunes. I can change this back bs I think that will still try to open the app if the user has it. It will outperform the link redirects sending people to itunes instead of the app fa it depends on what's more important to you. If you want to always send people to itunes or always have them open the app if they have it. Can you check again now from your phone? This link and the old instagram one? I changed it back but I still get redirected to itunes :s

**Comment by EmanHylooz** [comment]
hahahaha sorry sorry. 6ayyeb will check them again and get back to you.



Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by Farahalfayez** [comment]
@EmanHylooz It's changed now. Any user who opens a link should be redirected to the appstore after seeing a popup and clicking open.

**Comment by EmanHylooz** [comment]
Perfect, thanks a lot :)

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>
