### ISSUE TITLE
change keywords, Subtitle

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#137]
Keywords: كتاب,إلكتروني,تطبيق,قراءة,الكتب,تحميل,جرير,قارئ,arabic,novel,الروايات,مكتبة,نون,ياقوت,إلكترونية,read

Subtitle (under app name in app information): آلاف الكتب والروايات الإلكترونية بين يديك

**Comment by Shimaa-Hassan** [comment]
@Farahalfayez write here for any other changes

**Comment by Farahalfayez** [comment]
Done. @Shimaa-Hassan

**Comment by Shimaa-Hassan** [comment]
آلاف الكتب والروايات الإلكترونية بين يديك is big max 30 char

**Comment by Shimaa-Hassan** [comment]
@Farahalfayez

**Comment by Farahalfayez** [comment]
Fixed it @Shimaa-Hassan

**Comment by Shimaa-Hassan** [comment]
Ok
