### ISSUE TITLE
Analytics Tools Integration (27/8/2017)

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Technical#139]
We need to integrate with UXCam & Appsee. 

**UXCame:** 
https://uxcam.com/ and use:
Email: farah@abjjad.com
Password: abjjad@123

**Appsee**
https://www.appsee.com/ and use:
Email: farah@abjjad.com
Password: abjjad@123

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan please let us know as soon as integrations are done so we make use of free trial. 

@EmanHylooz we had the demo call with Appsee, the tool is amazing, after free trail they're open to discuss pricing.

**Comment by EmanHylooz** [comment]
@Nur-alfayez sounds great, really looking forward to see it with abjjad user. 

@Shimaa-Hassan Can you add it to Mahmoud's tasks? It should be an easy integration for both tools. I labeled it as priority 1.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan please give this a priority as it is easy to integrate (I hope :) and it is much needed nowadays, it is an amazing tool to see the user behavior recorded by video.  Please let me know if Mahmoud can do it. Especially that we want to take advantage of the free trial.

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz Farah accounts freetrial has ended

**Comment by Shimaa-Hassan** [comment]
do u need me to use another account ?

**Comment by EmanHylooz** [comment]
​Yes please, create a new account with a freetrial for both.​

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
@Nur-alfayez @Farahalfayez can you help shimaa if you can please? Maybe you can extend the same account or shall we just create new accounts?

**Comment by Shimaa-Hassan** [comment]
For some reason FreeTrial extended

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan great, is it extended for both? how many days extended? Let me know if you need us to contact them for anything.

**Comment by Shimaa-Hassan** [comment]
UXCAM => You have 14 days remaining of Pro plan trial
Appsee => Your trial will end in 11 days

**Comment by EmanHylooz** [comment]
So we are good to go?

**Comment by Nur-alfayez** [comment]
Tab let us know once integration is done and ill ask for a full free trial period. @Shimaa-Hassan

**Comment by Farahalfayez** [comment]
Hi guys,

Actually Ben from Appsee sent me this email: 

Dear Farah 

Happy Monday, and happy to see that you have ended up integrating and checking out Appsee :). 

As you registered well before integrating, I have extended your farah@abjjad.com trial account. Please feel free to log in, and spend more time with Appsee. 

Please feel free with any questions, comments, requests; I shall be happy to help. 

Best wishes 

@Nur-alfayez @EmanHylooz

**Comment by EmanHylooz** [comment]
@Nur-alfayez @Farahalfayez 
Shimaa is done integration and solved the performance issue. 
But to be able to start checking it out, we need to push the apps to store. Shimaa will push them today. Till we get them live on store (depending on iTunes), we can ask Ben to give us one month starting that date. 
Till now all we can do it wait till the releases gets approval on store.

**Comment by EmanHylooz** [comment]
By the way, it will be only Appsee for now, Shimaa removed UXCam so as not to harm the performance. We can test it anytime later, we can focus for now on Appsee.

**Comment by Farahalfayez** [comment]
@EmanHylooz I already talked to Ben, he said he will be happy to give us more time once everything is ok. Told him we were having problems with the SDK and still we didn't try it out in production.

**Comment by EmanHylooz** [comment]
Perfect. Thanks Farah.

Best,

Eman Hylooz

Founder & CEO | Abjjad

Jordan: +962.79.5402965 | Lebanon: +961.81.667918 | *www.abjjad.com*
<http://www.abjjad.com/>

**Comment by EmanHylooz** [comment]
The Appsee integration is done and ready on the store for both IOS and Android
