### ISSUE TITLE
Change pop up for locked books (Expected Delivery Sunday 10th End Of Day)

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Technical#149]
Remove the existing popup when a user clicks on a locked book and show the the popup I'll send you in email instead. 

Only do that for users who never tried free trial (not canceled/expired). For canceled/expired keep as is.

**Comment by EmanHylooz** [comment]
Starting: Sunday morning and deliver Sunday evening. (Amira)

**Comment by EmanHylooz** [comment]
Expected Start Date: Sunday the 10th of September
Expected Delivery: Sunday the 10th of September EOD
Assigned to: Amira

cc: @Nur-alfayez @Farahalfayez

**Comment by EmanHylooz** [comment]
@AmiraMostafaAhmed @Shimaa-Hassan 
I suggest we roll it back to old pop up and push again on IOS and Android store. Then we can solve the  issues as it is critical (crash). 

(Crash) 
1. In the book page, when I click on تحميل الكتاب and then the new pop up opens, I click on  مجاناً لشهر كامل it freezes and then it crashes the app (the android). 

(The UX) 
2. There are UX issues with the Loader (spinner), why did we use this Loader icon? The loading icon that we use inside all the other buttons is the default one and it appears inside the button not outside and it small and white not, check تحميل الكتاب for any free book for example). 
3. The pop up has big white space at the top, and the text is small and it is all centered while we can have it bigger and spread from top to bottom. (Just like the subscribe page).

**Comment by EmanHylooz** [comment]
Can you provide me with a test flight to test the pop up on IOS?

**Comment by EmanHylooz** [comment]
Found it, it is not crashing in IOS only in Android.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan if the crash is not going to take a lot of time to solve it, the let's solve it and push it right away on the google store (today)
If it will take time, then for Android roll back to the old pop up and push on google store. 

For the UX, @Nur-alfayez will tell you what exactly is the UX changes needed on both IOS and Android.

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  I will rollback until get all tested and confirmed.
We shouldn't release any version without take time to test all cases So sorry I should rollback to old version without deep linking and popup.

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan we cannot test the deeplinks if they are not on production. Don't roll back deep linking please as without it Farah & I cannot test it. (we won't use them untll we test them, so it is not critical if it is not working). 

As for the pop up, this only roll it back if you think it should be. The crash on Android was solved though in the new version you just released... so the UX issues are left only and it is okay to leave them as they are for now untill Nur talk to you.

And I agree, next time we cannot release something new without sending us to test it.
