### ISSUE TITLE
Locked Books Popup UX

### ISSUE THREAD

**Issue by Nur-alfayez** [EmanHylooz/Abjjad-Technical#159]
Hi Shimaa, 

Please check the image attached (the original design) and I'll explain what we need to fix in the popup (that was created): 

![artboard 1](https://user-images.githubusercontent.com/29916678/30520007-33372138-9bad-11e7-8ffd-96d4bec2a1e2.jpg)

This is what we need to do to make the live popup look closer to the one above: 

- Keep the size of the popup the same 
- Make the text ( هذا الكتاب متوفر من خلال... ) bigger and closer to the side edges and the X sign above (like in the photo above). The font is Roman, and the gray color is a bit darker.  
- The title should be bigger with the first line (read now through eshterak) a bit longer than the one under it. Make both close to the edges (like in the photo above). 
- Use the same font used in the homepage popup for "أبجد بلا حدود". 
- Make the button wider (same as in photo). And make text centered in the button. 
- The text under the button is more narrow and aligned with the button on 4 lines. Also make darker.
- Remove extra space after لمدة ٣٠ يوم
- آلاف وليس الآف
- نقطة بعد بسعر الكتاب الواحد 
- Remove (shoroo6 wa a7kam) because this is not the subscribe page (unless Apple will make trouble) 
- أكثر من ٢٠٠٠ كتاب.... make it same colors as the points under it. 
- Make this line ^ and the points under it bigger (like the photo attached)

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan Is this ready for testing?
