### ISSUE TITLE
Search Component Kit

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#174]
@EmanHylooz comments:

Ya36eekom el 3afyeh and great job! I tested the search, performance and scrilling is all good but there are few bugs:

1. When user clicks on search icon. The cursor should be by default active in the search box and keyboard activated too. (Check behaviour in current app).

2. The button تحميل الكتاب and the special cover image for ebooks are not appearing. (I guess because you still want to work on them?)

3. When searching for example نوال سعداوي not all the search results appear at the end, mostly last 10-20 books are missing (this is happening most of the times). Try searching on Andriod or web and then on testflight you will see the difderence in the search results. (The attached image shows the last book in test flight but this is not the last book in actual web search results for نوال سعداوي).

4. As for the loading indicator. Needs to also be added once the user searches and still waiting for the list to be loaded. Needs to be added on scroll too. But how are you thinking of adding it? Because the current load we have is not the best as it appears in the middle if the screen. Lets talk about this one.

![0](https://user-images.githubusercontent.com/1814104/34143641-68ce0fb4-e496-11e7-8888-9bed58f8daea.jpeg)

**Comment by Shimaa-Hassan** [comment]
"As for the loading indicator. Needs to also be added once the user searches and still waiting for the list to be loaded. Needs to be added on scroll too. But how are you thinking of adding it? Because the current load we have is not the best as it appears in the middle if the screen. Lets talk about this one. " we should add it in footer not in center.

**Comment by EmanHylooz** [comment]
> we should add it in footer not in center when scroll but add it in center when first search only.

Okay agreed. I just noticed that in testflight the search results performance where better, as in our current app the search results are slower because of the loading indicator (it keeps pausing when indicator appears). So just make sure that when adding this loading indicator it won't damage the performance the way it is in testflight now.

**Comment by EmanHylooz** [comment]
Great job (y)
