### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#44]
Use the link: https://developers.facebook.com/quickstarts/1422864911078454/?platform=ios to download SDK, follow the steps and add the following actions as app event: 

Install
Launch
Signup
Free trial
Subscription
Uninstall

**Comment by EmanHylooz** [comment]
Can you please add start and end date?

**Comment by EmanHylooz** [comment]
22-03-2017	26-03-2017

**Comment by Shimaa-Hassan** [comment]
Bug: Signup event fired when Signin
