### ISSUE TITLE
Firebase Analytics

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#46]
Use the link to download the SDK and add the Firebase to the app: https://firebase.google.com/docs/ios/setup
Add the Addsupprt framework: https://firebase.google.com/support/guides/analytics-adsupport
Add analytics & log the events mentioned previously in Facebook integration: https://firebase.google.com/docs/analytics/ios/start

**Comment by EmanHylooz** [comment]
Please add start and end date
