### ISSUE TITLE
Appsflyer

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#47]
Use the link to download SDK: https://support.appsflyer.com/hc/en-us/articles/207032066-AppsFlyer-SDK-Integration-iOS
Set up in-app events tracking API for the same events mentioned above. More details: https://support.appsflyer.com/hc/en-us/articles/207032116-AppsFlyer-Rich-In-App-Events-iOS
Test the SDK integration: https://support.appsflyer.com/hc/en-us/articles/115000262823-Testing-iOS-SDK-Integration

**Comment by EmanHylooz** [comment]
27-03-2017	29-03-2017
