### ISSUE TITLE
Improve All Books UI

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#57]
Exactly the same as IOS now with all the sub screens in (المزيد) and the التصنيفات. 
[https://github.com/EmanHylooz/Abjjad/issues/8](url)

**Comment by EmanHylooz** [comment]
Issues found so far: 
1. Review all the design elements to follow exact size and font as IOS (I have attached down a screenshot that shows the differences between IOS and Android and added a red number next to each one that has to be changed)
2. When I first sign up on abjjad, this screen loads without the tab bar. It should show the tab bar as soon as a user signs up (check IOS behaviour) 
3. The المزيد in كل الكتب  screen, for the different genres always get back the same list of books (الأدب), even when you click on المزيد  for الأاديان for example. 
4.  The  التصنيفات is not working when you click on any genre. 
5. The المزيد screen does not load more books while scrolling. 

![ios vs android](https://cloud.githubusercontent.com/assets/6830380/25615353/5f065782-2f3f-11e7-8429-eeaa5b3e1049.png)

**Comment by EmanHylooz** [comment]
1. All the APIs that get the different genres and (كتب مجانية ... الأكثر قراءة... الخ) are getting different sorting for the ebooks that we have in IOS. (especially the categories, where the eBooks do not show at the beginning of the list.) I believe the APIs used are incorrect. 
2. Make the purple banner a bit smaller in the height, and the font a bit smaller (so it would be like the IOS). 
3. The size of the books images, the ribbon seems to be bigger than IOS. Also the word مجاني  and  بلا حدود has to be in the middle of the ribbon. Make sure  everything in size (height and width) for the book and the ribbons are the same as IOS.

**Comment by Shimaa-Hassan** [comment]
All the APIs that get the different genres and (كتب مجانية ... الأكثر قراءة... الخ) are getting different sorting for the ebooks that we have in IOS. (especially the categories, where the eBooks do not show at the beginning of the list.) I believe the APIs used are incorrect.  "Solved"

**Comment by Shimaa-Hassan** [comment]
When sign in/sign up, the All Books page does not load the books images "Done"

**Comment by Shimaa-Hassan** [comment]
Note: The message that says لا يوجد اتصال بشبكة الإنترنت حاليا appears many times although I do have internet. #80  (Done)

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  is it happening alot ? "The horizental scroll does not load all the books."

**Comment by EmanHylooz** [comment]
@Shimaa-Hassan actually yesterday for the first time it worked, and then for many times it did not. I was surprised to see it work one time. Because most of the times it never worked.
