### ISSUE TITLE
Support My Subscriptions + Edit User's Account Settings

### ISSUE THREAD

**Issue by EmanHylooz** [EmanHylooz/Abjjad-Technical#60]
You can open WebView to Abjjad web Settings page.

The page "Edit Account" https://www.abjjad.com/member/editaccount to be shown as web view for those 4 sub pages:
تعديل الملف الشخصي
ربط الحساب مع مواقع التواصل
إعدادات الحساب
اشتراكي*

*This page will be hidden if the user is not subscribed at all or subscribed through Apple in app purchase, in those two cases the in app purchase will show or a page for اشتراكي from the native IOS.

This page will be shown only if user is subscribed through the web (no through the apple in app purchase), in that case the page اشتراكي will be a web view and the in app purchase should be hidden.

[https://github.com/EmanHylooz/Abjjad/issues/11](url)
[https://github.com/EmanHylooz/Abjjad/issues/17](url)

**Comment by EmanHylooz** [comment]
1. I cannot chose a photo in تعديل الملف الشخصي 
2, All the web pages do not have back button at the header (next to the logo) 
3. In the page اربط الحساب مع مواقع التواصل  when i click on اربط مع فيسبوك either nothing happens or a broken page opens.

**Comment by EmanHylooz** [comment]
Why cannot do a subscription using in app purchase? (although it gives me success) but does not reflect on the user as a subscriber (neither in app or in web).

**Comment by Shimaa-Hassan** [comment]
#75

**Comment by Shimaa-Hassan** [comment]
All the web pages do not have back button at the header (next to the logo) "Done"

**Comment by Shimaa-Hassan** [comment]
When I open a web view, the gadget on top that says "download the app" still shows although I am already in the app so it should not show. "Done"

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz  When I open a web view, the gadget on top that says "download the app" still shows although I am already in the app so it should not show. "Done"
Wait for deployment to test it

**Comment by EmanHylooz** [comment]
We have those left: 
1. In the page اربط الحساب مع مواقع التواصل when i click on اربط مع فيسبوك either nothing happens or a broken page opens.
2. When I open a web view, the gadget on top that says "download the app" still shows although I am already in the app so it should not show. (next release)
