### ISSUE TITLE
Free-trial Popup

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#88]
![0](https://user-images.githubusercontent.com/1814104/27277420-7d75d7be-54de-11e7-8d10-1dcb014668e2.jpeg)

**Comment by EmanHylooz** [comment]
In Android: 
- Pop up appears
- Click on إبدأ التجربة المجانية 
- The payment pop up appears, close it 
- The pop appears again with loading on the button  إبدأ التجربة المجانية 
- Close the pop up and go to the subscribe page, the loading in still there and i cannot
 click the button 

Correct scenario: if i clicked the إبدأ التجربة المجانية  once, the pop up closes and does not appear anymore and no loading effect sticks to the button  (Check IOS behavior) 
![screenshot_20170717-145325](https://user-images.githubusercontent.com/6830380/28269073-5d192d36-6b09-11e7-82f3-2eeeaa9f4e59.png)
