### ISSUE TITLE
Integrate Instabug

### ISSUE THREAD

**Issue by Shimaa-Hassan** [EmanHylooz/Abjjad-Technical#95]

**Comment by MahmoudAlyIbrahim** [comment]
done

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz we integrated it. so let's upgrade to bronze to continue use it.

**Comment by Shimaa-Hassan** [comment]
@Nur-alfayez

**Comment by Nur-alfayez** [comment]
Great, thanks Shimaa. Let me check the plans - I was hoping I can try it on freetrial but must have expired by now.

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan the integration isn't showing yet, I talked with the support team and they say it is not integrated.. I thought it could be because we did not release yet but here is what they said: 

_It hasn't to be released, you can use the Beta mode for beta testing, however integrating the SDK is not related to releasing the app :)_

I got an extension for the free trial until July 24, so it would be great if we get to test before then.

**Comment by Shimaa-Hassan** [comment]
We integrated it and tested in another account with freetrial enabled because freetrial in this account has end before we start integration. 
but it is extended so I will change keys to abjjad current account and send u new releases.

**Comment by Nur-alfayez** [comment]
Aaah ok, mystery solved. Thank you

**Comment by MahmoudAlyIbrahim** [comment]
@Nur-alfayez i need android application to be created so please create a one or give us an admin privilige

**Comment by Nur-alfayez** [comment]
Done.

On Mon, Jul 17, 2017 at 2:39 PM, MahmoudAlyIbrahim <notifications@github.com

**Comment by Nur-alfayez** [comment]
@MahmoudAlyIbrahim, the SDK automatically use the device's current locale, however, we want to override it by the following method to instabug builder: Instabug.setLocale(Locale.ARABIC);  can you change the language to Arabic in iOS and Android please? 

https://docs.instabug.com/docs/android-locale

**Comment by Shimaa-Hassan** [comment]
@EmanHylooz @Nur-alfayez we should activate instabug now, free trial is expired. we need it now because we solve crashes appeared there.

**Comment by EmanHylooz** [comment]
@Nur-alfayez please send me details to pay for it.

**Comment by Nur-alfayez** [comment]
Hi Shimaa,

Can you give us a couple of days as we negotiate the price with them.

Thanks,
Nur

**Comment by Shimaa-Hassan** [comment]
Ok

**Comment by Nur-alfayez** [comment]
@Shimaa-Hassan we've upgraded. I'll close this issue.
